services:
  - type: web
    name: digital-bevy-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn backend.wsgi:application --preload --workers=2 --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        value: change_me
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: your-service.onrender.com
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: GITHUB_TOKEN
        sync: false
